### ISSUE TITLE
Can't start sample application

### ISSUE THREAD

**Issue by wkloki** [QuickBlox/quickblox-react-native-samples#4] opened 2020-07-26 14:17 UTC
![image](https://user-images.githubusercontent.com/15138432/88481354-911a9c00-cf8d-11ea-8859-43dc0a78f84c.png)

i have this error after running this "react-native run-android". Please advise.

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:48
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by Vikasatneaxus** [comment] 2021-08-19 06:48
i am facing the same problem ,pls provide me the solution.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-05 15:49
@wkloki @Vikasatneaxus Hello,

This is Nikolay from QuickBlox support.

In order to investigate the issue, please provide me with these points:
1. Version of the QuickBlox React Native SDK.
2. Platform where the issue is reproduced (Android, iOS, or both).
3. Version of the platform (e.g. Android 11, iOS 13).
4. Device models.
5. React Native version.
6. Information from  react-native info.
7. Information from  npm list.
8. Steps to reproduce the issue.
9.  Please provide us with full REST + XMPP logs if they can be gathered as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 13:13
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 13:13 UTC
