### ISSUE TITLE
Order of messages are getting swapped while chatting in ios

### ISSUE THREAD

**Issue by LinuiLeaf** [QuickBlox/quickblox-react-native-samples#7] opened 2020-12-22 05:08 UTC
Hi,

I've tried the chat sample for react native.The issue now I'm facing in ios is when two users are chatting the order of messages  are not proper. But whenever I leave from the chat box and take the chat again the order will be fine.Getting this issue only when two users are chatting in online.Please find the working video of the issue that I'm facing.

https://user-images.githubusercontent.com/52774947/102851218-4409fb80-4441-11eb-9086-3e122a39a429.mov

**Comment by dheereshaggarwal** [comment] 2021-01-25 11:32
It probably happens because by default all the messages go to the right side in this app in Android, no matter who is the receiver or the sender, this is the problem I am also facing

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-06 09:20
Hello @LinuiLeaf 

This is Nikolay from QuickBlox support.

Please try using the latest version of the SDK:
[https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)

If the issue persists, please provide me with the following points:
1. Version of QuickBlox React Native SDK.
2. Platform where the issue is reproduced (Android, iOS, or both).
3. Version of the platform (e.g. Android 11, iOS 13).
4. Device models.
5. React Native version.
6. Information from react-native info.
7. Information from npm list.
8. Please provide full REST + XMPP logs as an attachment in .txt format.
You may use this guide: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 13:14
@LinuiLeaf The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 13:14 UTC
